### ISSUE TITLE
AttributeError: 'Mail' object has no attribute 'set_template_id'

### ISSUE THREAD

**Issue by bmull** [sklarsa/django-sendgrid-v5#107]
I'm following instructions from the README, using Django 3.1.6, Python 3.7.7, django-sendgrid-v5==0.6.8
and tried to send an email with a template ID. I get the error `AttributeError: 'Mail' object has no attribute 'set_template_id'`

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../venv/lib/python3.7/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/.../venv/lib/python3.7/site-packages/sendgrid_backend/mail.py", line 52, in send_messages
    data = self._build_sg_mail(msg)
  File "/.../venv/lib/python3.7/site-packages/sendgrid_backend/mail.py", line 93, in _build_sg_mail
    mail.set_template_id(msg.template_id)
AttributeError: 'Mail' object has no attribute 'set_template_id'
```

**Comment by sklarsa** [comment]
I recommend upgrading to a more recent version of django-sendgrid-v5 to ensure compatibility with more recent django apis
