### ISSUE TITLE
Sending fails with empty email subject.

### ISSUE THREAD

**Issue by seospace** [sklarsa/django-sendgrid-v5#20]
I am using built-in Django PasswordResetView.
When using empty email subject in "password_reset_subject.txt" this is what happens.

https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.views.PasswordResetView

````
[29/Mar/2018 16:13:06] "GET /konto/odzyskiwanie/ HTTP/1.1" 200 454
Internal Server Error: /konto/odzyskiwanie/
Traceback (most recent call last):
  File "...lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "...lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "...lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "...lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "...lib\site-packages\braces\views\_access.py", line 128, in dispatch
    request, *args, **kwargs)
  File "...lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "...lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "...lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "...lib\site-packages\django\contrib\auth\views.py", line 406, in dispatch
    return super().dispatch(*args, **kwargs)
  File "...lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "...lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "...lib\site-packages\django\contrib\auth\views.py", line 419, in form_valid
    form.save(**opts)
  File "...lib\site-packages\django\contrib\auth\forms.py", line 297, in save
    email, html_email_template_name=html_email_template_name,
  File "...lib\site-packages\django\contrib\auth\forms.py", line 251, in send_mail
    email_message.send()
  File "...lib\site-packages\django\core\mail\message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "...lib\site-packages\sendgrid_backend\mail.py", line 66, in send_messages
    self.sg.client.mail.send.post(request_body=data)
  File "...lib\site-packages\python_http_client\client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "...lib\site-packages\python_http_client\client.py", line 161, in _make_request
    raise exc
python_http_client.exceptions.BadRequestsError: HTTP Error 400: Bad Request
[29/Mar/2018 16:13:08] "POST /konto/odzyskiwanie/ HTTP/1.1" 500 171542
````

**Comment by sklarsa** [comment]
The sendgrid API requires a subject.  https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.subject

I wish the error message returned from the sendgrid-python library was better, but that's a different issue that needs to be addressed there :-(

**Comment by seospace** [comment]
Can we make like if email.subject == '' raise exception?

**Comment by sklarsa** [comment]
I'm not sure if that will work or not.  If it doesn't, maybe just try 1 space like this `email.subject = " "`
