### ISSUE TITLE
Duplicate emails in recipient_list raises exception and crashes

### ISSUE THREAD

**Issue by daxm** [sklarsa/django-sendgrid-v5#78]
If I put the same email address twice in the recipient_list list the system will crash.

Why would I do that?  Well, I'm "CC'ing" a central email address when any emails are sent from my Django server.  It just happened that one of the users has the same email address as this central email address.

A simple "if x_email == y_email" statement fixes it on my end but I would imagine it should be fixed internally.

Traceback:
Traceback (most recent call last):
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/IVR/views.py", line 116, in send_email
    send_mail(
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/sendgrid_backend/mail.py", line 129, in send_messages
    resp = self.sg.client.mail.send.post(request_body=data)
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/python_http_client/client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/home/daxm/PycharmProjects/SHP_Twilio_Phone_System/venv/lib/python3.8/site-packages/python_http_client/client.py", line 184, in _make_request
    raise exc

**Comment by sklarsa** [comment]
Do you have details on what the raised exception is?  My guess is it's a 4xx response from the sendgrid server, which should provide some additional context on why the request failed.
